### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by Galerici** [TheSeromitschu/Discord-VanityURL-Guard#1]
Hocam bot başlamıyor hata yok , cmd boş.

**Comment by TheSeromitschu** [comment]
Merhaba @Galerici. Botun intentlerinin açık olması gerekiyor. Açık değilse sorun oradadır.

**Comment by Galerici** [comment]
Cevap için teşekkürler fakat intentler açık.

**Comment by TheSeromitschu** [comment]
Müsait bir zamanda botu kendim tekrar deneyip size dönücem eğer çalışmıyorsa projeyi yenilerim. İyi günler.

**Comment by Galerici** [comment]
Tamamdır.
